name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          repo-token: ${{ github.token }}
          repository: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}

      - run: npm ci
      - run: npm run check
      - run: npm run build:lib

      - name: Coveralls GitHub Action
        if: matrix.node-version == '14.x'
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
