name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm ci
      - run: npm run check
      - run: npm run test

      - name: Coveralls GitHub Action
        if: matrix.node-version == '14.x'
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
